spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/girlsdb?useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource